use_frameworks!

target 'PaySDK_Example' do
  pod 'PaySDK', :path => '../'

  target 'PaySDK_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
